# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: golang
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: course
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080